Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
KeyboardInterrupt
Traceback (most recent call last):
  File "./main_uti.py", line 4, in <module>
    import numpy
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/core/__init__.py", line 104, in <module>
    from . import _add_newdocs
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/core/_add_newdocs.py", line 4470, in <module>
    """)
  File "/home/divesh/Desktop/thesis/venv/lib/python3.6/site-packages/numpy/core/function_base.py", line 506, in add_newdoc
    new = getattr(__import__(place, globals(), {}, [obj]), obj)
ImportError: numpy.core.multiarray failed to import
